#!/usr/bin/env python
#####################################################################
#
# fasta_rotate
#
# Authors: Lauren Lui and Torben Nielsen
#
# Usage: python fasta_rotate <bp offset> <fasta file>
#
#####################################################################

import sys
import itertools

offset = int(sys.argv[1])
with open(sys.argv[2]) as f:
    for header,group in itertools.groupby(f, lambda x: x[0] == '>'):
        if header:
            defline_id = next(group)[1:].rstrip()
        else:
            dna_sequence = ''.join(line.strip() for line in group)
            print(">" + defline_id)
            print(dna_sequence[offset:] + dna_sequence[0:offset])
